# 1. Ve a la pagina de tu proyecto en SonarCloud
# 2. Busca "Project Key" y "Organization Key" (suelen estar a la derecha en 'Information')

sonar.projectKey=la-ley-del-corazon_maze-rush-frontend
sonar.organization=la-ley-del-corazon

# Rutas
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.tsx,**/*.test.ts

# Exclusiones (Lo mismo que pusimos en vite.config.ts)
sonar.exclusions=**/*.test.tsx,**/*.css,**/*.module.css,src/main.tsx,src/vite-env.d.ts

# IMPORTANTE: La ruta al reporte que genera Vitest
sonar.javascript.lcov.reportPaths=coverage/lcov.info